apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
spec:
  project: k3s-setup
  source:
    repoURL: https://github.com/charti/k3s-setup.git
    targetRevision: main
    path: charts/istio/gateway
    helm:
      releaseName: gateway
      valueFiles:
      - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
