apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
spec:
  project: k3s-setup
  source:
    repoURL: https://github.com/charti/k3s-setup.git
    targetRevision: main
    path: charts/istio/gateway-1.25.1.tgz
    chart: gateway
    helm:
      releaseName: gateway
      valueFiles:
      - ../../helm-values/istio/ingress-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
