apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingress
  namespace: argocd
spec:
  project: k3s-setup
  source:
    repoURL: https://istio-release.github.io/istio-charts
    chart: gateway
    targetRevision: 1.25.1
    helm:
      releaseName: istio-ingress
      valueFiles:
      - ../../helm-values/istio/ingress-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
